// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:62785662600:web:8941b8d31c999b8c6df93d',
    messagingSenderId: '62785662600',
    projectId: 'piscine-mobile',
    authDomain: 'piscine-mobile.firebaseapp.com',
    storageBucket: 'piscine-mobile.appspot.com',
    measurementId: 'G-JZ011JQE97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:62785662600:android:31306a985b417c086df93d',
    messagingSenderId: '62785662600',
    projectId: 'piscine-mobile',
    storageBucket: 'piscine-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:62785662600:ios:787e653ce3388ebb6df93d',
    messagingSenderId: '62785662600',
    projectId: 'piscine-mobile',
    storageBucket: 'piscine-mobile.appspot.com',
    iosClientId: '62785662600-g0chru8hdbfoajhvau5r32vm2ba0dae1.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:62785662600:ios:787e653ce3388ebb6df93d',
    messagingSenderId: '62785662600',
    projectId: 'piscine-mobile',
    storageBucket: 'piscine-mobile.appspot.com',
    iosClientId: '62785662600-g0chru8hdbfoajhvau5r32vm2ba0dae1.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:62785662600:web:ef5526ae2d5020216df93d',
    messagingSenderId: '62785662600',
    projectId: 'piscine-mobile',
    authDomain: 'piscine-mobile.firebaseapp.com',
    storageBucket: 'piscine-mobile.appspot.com',
    measurementId: 'G-SFNBLJ55HD',
  );
}
